name: update

on:
  schedule:
    - cron: "0 20 * * 3"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: garpeln.github.io
        run: |
          git config --local user.email "garpeln@163.com"
          git config --local user.name "garpeln"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps my blog active"
          git push
